### ISSUE TITLE
Gravity is funky when leaving a vehicle

### ISSUE THREAD

**Issue by jellyton69** [Blu-x92/LunasFlightSchool#1]
After exiting a vehicle it seems the entity floats around as if it's on moon gravity. Makes it really difficult to actually land properly.

**Comment by Blu-x92** [comment]
thats source. when the vehicle is landed there isnt any code running on it. i could try to tweak the inertia a bit but it wont make much of a difference. Also i dont experience any problems with the actual landing procedure so i dont see how this is an issue
