### ISSUE TITLE
Engine Off (To Simulate Engine Failure) = Drop Like A Brick & No Control

### ISSUE THREAD

**Issue by KaptianCore** [Blu-x92/LunasFlightSchool#13]
@Luna would be really nice if u make it that my helicopter doesn't drop like a brick and I can still control the vehicle when I turn the engine off to simulate a engine failure as with WAC I can auto rotate down but not with LFS please fix <3

**Comment by Blu-x92** [comment]
dropping like a brick without control is exactly what happens when you turn off the rotors on a heli…
Also this is for issues and not suggestions...

**Comment by KaptianCore** [comment]
When engine failures happen pilots can auto rotate down
