### ISSUE TITLE
Teleportation Glitch

### ISSUE THREAD

**Issue by oninoni** [Blu-x92/LunasFlightSchool#16]
The ships bug out and jump around when teleported. 
This can be reproduced by just flying a ship into a teleporter on a map (for example the Deathstar map by KingPommes)
Seems like it's a problem with the smoothing of the Flight Direction relative to the Teleport.
I dont understand the code enough however, to allow fixing of this by myself.

**Comment by js1251** [comment]
Heres a video showing this phenomenon:
[https://youtu.be/vPWO8AFrGKo?t=89]

**Comment by Blu-x92** [comment]
flight direction isn't smoothed. It's a problem with how ENT:GetWingVelocity(), ENT:GetElevatorVelocity() and ENT:GetRudderVelocity() is calculating the velocity based on position changes per tick

**Comment by js1251** [comment]
Interesting insight thank you. If possible a fix would benefit LFS.

If anyone with the same issue is stumbling upon this, **this is a crude workaround** that seems to work ok:
The function "LFSEnter()" is called from the map **whenever something touches a teleport** trigger via a **lua_run entity**.
Ive been told by Oni that the timer might not work so well on low tick servers.

```
-- Thanks Oni for helping with this

local function startEngine(ship)
	if ship:GetEngineActive() or ship:IsDestroyed() or ship:InWater() or ship:GetRotorDestroyed() then return end

	ship:SetEngineActive( true )
	ship:OnEngineStarted()

	ship:InertiaSetNow()
end

function LFSEnter()
	local ship = ACTIVATOR
	if IsValid(ship) and ship.LFS then
		if ship:GetEngineActive() then
			ship:StopEngine()
			timer.Simple(0.1, function() startEngine(ship) end)
		end
	end
end
```
