### ISSUE TITLE
Auto AI + No-Collision Change Not Made on Gunship Base

### ISSUE THREAD

**Issue by jellyton69** [Blu-x92/LunasFlightSchool#19]
In regards to the new update:
AI is not automatically enabled when spawning a ship (while being in a ship) that is based off of the gunship base.

Additionally, any ship on the gunship base is also not no-collided with other ships.

(Small note: I think leaving collisions on is a better choice. It adds another bit of challenge and awareness a pilot needs to have in the sky (or in space). If you were to bring collisions back, having a timer to switch collisions on after a bit to keep the auto-ai functionality useable would be nice.)
or a config option could be added in the form of a convar for turning on/off the collisions

**Comment by Blu-x92** [comment]
Gunships still having collisions is intentional. Not sure about adding an extra setting for nocollide but i can revert this if it pisses off too many people

**Comment by Blu-x92** [comment]
#20
is this better?

player on player will collide
ai on ai won't collide
ai on player will collide

uploading now, pls feedback

**Comment by jellyton69** [comment]
That's perfect. Thank you.
