### ISSUE TITLE
Reducing lag/delay with your traces

### ISSUE THREAD

**Issue by StarLight-Oliver** [Blu-x92/LunasFlightSchool#2]
Most of your traces from what I can see you are using this for the filter
`filter = function( e )
	local collide = e ~= self
	return collide
end`

However, you should just be able to do 
`filter = self,`
and if you want multiple ents then just use a table. This should be faster. If you choose to keep using the function you can just do `return e ~= self` without defining the variable. But this has almost 0 effects on performance.

[http://wiki.garrysmod.com/page/Structures/Trace](Source)

**Comment by Blu-x92** [comment]
oh thanks for reminding. Haven't touched this part of the Code since initial release
