### ISSUE TITLE
No Colliding Vehicles

### ISSUE THREAD

**Issue by SniperJohn335** [Blu-x92/LunasFlightSchool#20]
I believe that the LFS vehicles being no-collided will benefit the AI, but will affect the PVP setting in a bad way. I believe that this will reduce the amount of skill needed to fly proficiently, and while it does combat the kamikaze type playstyles it just adds a different one. This allows players to have no risk when tailing you and doesn't punish bad pilots who run into people. A solution to this would be adding the ability to turn this off and possibly adding an option to have AI vehicles not collide with each other for x amount of time of being spawned, lets say 5-10 seconds. This would combat the spawning issues that sometimes happen with AI but would still allow them to collide with other vehicles after that initial time.

This is just an addition that I would like, maybe it's just me but for PVP or even PVE in some cases I think it would be more "fun" to have to use more skill when flying.

**Comment by Blu-x92** [comment]
see #19
