### ISSUE TITLE
Ai spawner not overriding teams

### ISSUE THREAD

**Issue by Trooper025** [Blu-x92/LunasFlightSchool#21]
I wanted to let you know about a small bug I encountered when using the AI spawner: for some reason, any vehicle spawned by it doesn't have their team changed, and instead uses the one it would default to if spawned in via the spawn menu. For example, since the P-47D's team is preset to Team 2, it will spawn in with the AI on Team 2, regardless of what team I set the spawner for. Similarly, the BF 109, set to Team 1 when the player spawns it in, spawns with the AI on Team 1 regardless of the spawner's set team. I encountered this a few days ago and wanted to see if any other addons were conflicting, and even messed around with the console commands. I haven't come to any good conclusions, other than it being something related to the base addon itself. I think I remember encountering a similar bug months ago but I don't remember what I did to fix it. I'm don't understand much of Lua, my only experience being basic sweps, so if there's any insight you might have, I'd be glad to hear it. Thank you.

**Comment by Blu-x92** [comment]
the entity itself works fine, there hasnt been any changes. The issue is the edit properties menu being anal about the slider being set exact or it doesnt update on server. Its a gmod issue. Try typing in the number exactly and wiggle the slider around a bit

**Comment by Trooper025** [comment]
Thank you!
