### ISSUE TITLE
AI attacking ground NPCs and players

### ISSUE THREAD

**Issue by militaristica** [Blu-x92/LunasFlightSchool#25]
I thought this was already a feature, apparently it's not. IMO should've been already added.
It'd probably be cool if the AI for helicopters and planes could shoot at players and NPCs on the ground.
Way to implement this could be a toggle option in the LFS menu, and when adding AI to a vehicle via properties having a "NPC team" slider thru 1-2, with 1 being on the citizen/rebel/friendly side, and 2 being on the combine/hostile side. Depending on the team, they attack the cooresponding enemies on the ground.

**Comment by Blu-x92** [comment]
they already do attack players and npcs
