### ISSUE TITLE
LFS AI Teams do not stay the same when permapropped.

### ISSUE THREAD

**Issue by KekkyShmekky** [Blu-x92/LunasFlightSchool#31]
I've tried this with the Rebel Heli and Cessna, and their teams were stuck at 2 and 0 respectively. I'm wondering if the issue is here or with Permaprops.

**Comment by Blu-x92** [comment]
i have no control over what is saved in permaprops as those variables are just DTvars that come with the game. permaprops is probably missing a timer on spawn to wait after defaults have been set // doesnt save or set them at all
